---
- name: Get leappctl repository
  git:
      repo: "{{ cli.git.repo }}"
      dest: "{{ cli.git.dest }}"
      version: "{{ cli.git.version }}"

- name: Install leappctl dependencies
  become: true
  shell: "cd {{ cli.git.dest }} && make install-deps"

- name: Build leappctl dependencies
  shell: "cd {{ cli.git.dest }} && make build"

- name: Install leappctl
  become: true
  shell: "cd {{ cli.git.dest }} && make install"
