---
- name: Get leappctl repository
  git:
      repo: "{{ cli.git.repo }}"
      dest: "{{ cli.git.dest }}"
      version: "{{ cli.git.version }}"

- name: Install & build Leappctl
  block:
    - become: "{{ item.become }}"
      shell: "cd {{ cli.git.dest }} && make {{ item.name }}"
      with_items: "{{ common.build_steps }}"
