---
snactor:
    copr_repo: "evilissimo/leapp"
    git_repo: https://github.com/leapp-to/snactor.git
    git_dest: "{{ common.workdir }}/snactor/"
    conf_file: "{{ lookup('env', 'HOME')  }}/.snactor.cfg"
    package: "python-snactor"
