---
common:
    build_steps:
        - name: install-deps
          become: true
        - name: build
          become: false
        - name: install
          become: true
    paths:
        tito: "{{ lookup('env', 'HOME') }}/leapp/pkgs"
        workdir: "{{ lookup('env', 'HOME') }}/leapp"
    packages:
        python: python2
        epel: epel-release
        deps:
            - git
            - sudo
            - make
            - tito
            - python2-pip
            - libselinux-python
