---
- name: Install packages required by daemon on Fedora, if necessary
  become: true
  dnf:
      name: "{{ item }}"
      state: present
  with_items: "{{ daemon.packages.fedora }}"
  when: ansible_distribution == 'Fedora'

- name: Install packages required by daemon on CentOS, if necessary
  block:
    - name: Install packages required by daemon on CentOS, if necessary
      become: true
      yum:
        name: "{{ item }}"
        state: present
      with_items: "{{ daemon.packages.centos }}"
    - name: Go get missing packages required by daemon on CentOS, if necessary
      raw: "go get -u {{ item }}"
      with_items: "{{ daemon.missing.centos }}"
  when: ansible_distribution == 'CentOS'

- name: Use go get to download leapp daemon and dependencies
  raw: "go get {{ daemon.git.repo }}/..."

- name: Install the Leapp-go dependencies and build it
  shell: "cd {{ daemon.link.src }} && make install-deps build"

- name: Install the Leapp-go binaries
  become: true
  shell: "cd {{ daemon.link.src }} && make install"

- name: Add a symlink for daemon code to leapp working dir
  file:
      src: "{{ daemon.link.src }}"
      dest: "{{ daemon.link.dest }}"
      state: link
