---
- name: Install dnf-plugins-core to enable using copr repositories
  become: true
  dnf:
      name: dnf-plugins-core
      state: present

- name: Enable leapp repository
  become: true
  raw: "dnf copr enable -y {{ snactor.copr.repo }}"

- name: Get snactor build dependencies
  raw: "dnf repoquery -C --arch src --requires {{ snactor.package }} 2> /dev/null"
  register: builddeps

- name: Install packages required while building snactor, if necessary
  become: true
  dnf:
      name: "{{ item }}"
      state: present
  with_items: "{{ builddeps.stdout_lines }}"

- name: Get snactor dependencies
  raw: "dnf repoquery -C --requires {{ snactor.package }} 2> /dev/null"
  register: pkgdeps

- name: Install packages required by snactor, if necessary
  become: true
  dnf:
      name: "{{ item }}"
      state: present
  with_items: "{{ pkgdeps.stdout_lines }}"

- name: Get snactor repository
  git:
      repo: "{{ snactor.git.repo }}"
      dest: "{{ snactor.git.dest }}"
      version: "{{ snactor.git.version }}"

- name: Build and install snactor package
  become: true
  command: "tito build --rpm -o {{ common.paths.tito }} -i"
  args:
      chdir: "{{ snactor.git.dest }}"

- name: Create snactor conf file
  file:
      path: "{{ snactor.conf.file }}"
      state: touch
      mode: 0644
