---
- name: Get snactor repository
  git:
      repo: "{{ snactor.git.repo }}"
      dest: "{{ snactor.git.dest }}"
      version: "{{ snactor.git.version }}"

- name: Install & build Snactor 
  block:
    - become: "{{ item.become }}"
      shell: "cd {{ snactor.git.dest }} && make {{ item.name }}"
      with_items: "{{ common.build_steps }}"
