---
- name: Get snactor repository
  git:
      repo: "{{ snactor.git.repo }}"
      dest: "{{ snactor.git.dest }}"
      version: "{{ snactor.git.version }}"

- name: Install snactor package dependencies
  become: true
  shell: "cd {{ snactor.git.dest }} && make install-deps"

- name: Build snactor package
  shell: "cd {{ snactor.git.dest }} && make build"

- name: Install snactor package
  become: true
  shell: "cd {{ snactor.git.dest }} && make install"

- name: Create snactor conf file
  file:
      path: "{{ snactor.conf.file }}"
      state: touch
      mode: 0644
