---
- name: Install dnf-plugins-core to enable using copr repositories
  become: true
  become_method: sudo
  dnf:
      name: dnf-plugins-core
      state: present

- name: Enable leapp repository
  become: true
  become_method: sudo
  raw: "dnf copr enable {{ snactor.copr_repo }} -y"

- name: Install packages required by snactor, if necessary
  become: true
  become_method: sudo
  dnf:
      name: "{{ item }}"
      state: present
  with_items: "{{ snactor.packages }}"

- name: Get snactor repository
  git:
      repo: "{{ snactor.git_repo }}"
      dest: "{{ snactor.git_dest }}"

- name: Run install target
  make:
      chdir: "{{ snactor.git_dest }}"
      target: install
  become: true
  become_method: sudo

- name: Create snactor conf file
  file:
      path: "{{ snactor.conf_file }}"
      state: touch
      mode: 0644
