daemon:
    git:
        repo: github.com/leapp-to/leapp-go
    link:
        src: "{{ lookup('env', 'HOME') }}/go/src/github.com/leapp-to/leapp-go"
        dest: "{{ common.paths.workdir }}/leapp-go"
    packages:
        - golang
        - golang-googlecode-tools-goimports
        - golint
