---
- name: Get leapp actors main repository
  git:
      repo: "{{ actors.git.repo }}"
      dest: "{{ actors.git.dest }}"
      version: "{{ actors.git.version }}"

- name: Install packages required by some actors, if necessary
  become: true
  package:
      name: "{{ item }}"
      state: present
  with_items: "{{ actors.packages }}"

- name: Install & build Leapp actors
  block:
    - become: "{{ item.become }}"
      shell: "cd {{ actors.git.dest }} && make {{ item.name }}"
      with_items: "{{ common.build_steps }}"
