---
- name: Get leapp actors main repository
  git:
      repo: "{{ actors.git.repo }}"
      dest: "{{ actors.git.dest }}"
      version: "{{ actors.git.version }}"

- name: Install packages required by some actors on Fedora, if necessary
  become: true
  dnf:
      name: "{{ item }}"
      state: present
  with_items: "{{ actors.packages }}"
  when: ansible_distribution == 'Fedora'

- name: Install packages required by some actors on CentOS, if necessary
  become: true
  yum:
      name: "{{ item }}"
      state: present
  with_items: "{{ actors.packages }}"
  when: ansible_distribution == 'CentOS'

- name: "Install Leapp-Actors dependencies"
  become: true
  shell: "cd {{ actors.git.dest }} && make install-deps"

- name: "build Leapp-Actors"
  shell: "cd {{ actors.git.dest }} && make build"

- name: "Install Leapp-Actors"
  become: true
  shell: "cd {{ actors.git.dest }} && make install"
